[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 300

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

# [cursor.style]
# shape = "Block"

# [env]
# TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
# family = "JetBrainsMono Nerd Font"
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font"
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font"
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/github-dark-high-contrast.toml"
]
